# Numpy - Numerical Python

-https://datascienceschool.net/01%20python/03.02%20%EB%B0%B0%EC%97%B4%EC%9D%98%20%EC%83%9D%EC%84%B1%EA%B3%BC%20%EB%B3%80%ED%98%95.html

In [4]:
# de facto standard
import numpy as np

## 1. ndarray(Numpy Dimensional Array)

In [5]:
a = np.array([1, 4, 5, 8], float)
print(a)        # 리스트와 다르게 , 가 안붙음

[1. 4. 5. 8.]


In [6]:
a[3], a.dtype, a.shape

(8.0, dtype('float64'), (4,))

## 2. Array shape

In [7]:
# 1차원 - vector
a = np.array([1, 4, 5, 8], float)

In [9]:
# 2차원 - matrix
m = [[1, 4], [5, 8]]
b = np.array(m, float)          # (데이터, 데이터타입)
print(b)

[[1. 4.]
 [5. 8.]]


In [10]:
# 3차원 - tensor
t = [[[1, 4], [5, 8]], [[11, 14], [15, 18]]]
c = np.array(t, float)
c

array([[[ 1.,  4.],
        [ 5.,  8.]],

       [[11., 14.],
        [15., 18.]]])

In [11]:
a.shape, b.shape, c.shape       # 1차원, 2차원, 3차원  / element가 몇개냐

((4,), (2, 2), (2, 2, 2))

In [13]:
# ndim - 행렬의 차원
a.ndim, b.ndim, c.ndim

(1, 2, 3)

In [14]:
# size
a.size, b.size, c.size

(4, 4, 8)

In [15]:
# data type(dtype)
c = np.array(t, dtype = np.float32)
c

array([[[ 1.,  4.],
        [ 5.,  8.]],

       [[11., 14.],
        [15., 18.]]], dtype=float32)

- reshape: size(element의 갯수)는 동일

In [16]:
c.reshape(2, 4).shape

(2, 4)

In [17]:
c.reshape(2, 4)

array([[ 1.,  4.,  5.,  8.],
       [11., 14., 15., 18.]], dtype=float32)

In [18]:
c.reshape(8, )      # element의 개수는 변하지않는다

array([ 1.,  4.,  5.,  8., 11., 14., 15., 18.], dtype=float32)

In [19]:
# -1은 한번만 사용 가능 / 사이즈를 알기 때문에 사용 가능하다..!
c.reshape(-1, 4)        # 끝에를 4개로 맞추고나면 나머지들(-1)로 맞춰라

array([[ 1.,  4.,  5.,  8.],
       [11., 14., 15., 18.]], dtype=float32)

In [20]:
# flatten - 1차원으로 변환
c.flatten()

array([ 1.,  4.,  5.,  8., 11., 14., 15., 18.], dtype=float32)

## 3. Indexing and Slicing
- numpy에서는 2차원도 슬라이싱이 가능하다

In [23]:
a = np.arange(6)       # a = np.array(range(6)) 와 같다
a

array([0, 1, 2, 3, 4, 5])

In [25]:
a = np.arange(6).reshape(2, 3)      # 2차원의 요소3개의 매트릭스 생성
a

array([[0, 1, 2],
       [3, 4, 5]])

In [26]:
a[0][1]

1

In [27]:
a[0][1], a[0,1]     # a[0,1] : 행인덱스, 열인덱스 - []를 한번만 사용해서 간단히 보기

(1, 1)

In [28]:
# 리스트와는 달리 행,열 모두에 대해 슬라이싱 가능
a[:, :2]        # : (행은 전체행에서) , :2(처음이랑 두번째꺼만 가져옴)

array([[0, 1],
       [3, 4]])

In [52]:
b = np.arange(16).reshape(-1, 4)
b

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [31]:
# 5,6,9,10만 추출
b[1:3, 1:3]

array([[ 5,  6],
       [ 9, 10]])

In [32]:
# 0, 1, 4, 5, 8, 9 추출
b[:3, :2]       # 또는 b[0:3, 0:2] / 0은 생략 가능

array([[0, 1],
       [4, 5],
       [8, 9]])

In [53]:
# 세번째 열까지는 X, 마지막 열은 Y
X, Y = b[:, :-1], b[:, -1]   # 두번째 b[-1] 은 마지막 열만! 가져온다
X.shape, Y.shape    # Y.shape는 (4,1)이지만 결과에 1이 생략

((4, 3), (4,))

In [54]:
X

array([[ 0,  1,  2],
       [ 4,  5,  6],
       [ 8,  9, 10],
       [12, 13, 14]])

In [55]:
Y

array([ 3,  7, 11, 15])

## 4. Creation

In [34]:
np.arange(1, 10)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [35]:
np.arange(0, 1.1, 0.1)      # numpy는 소수점 사용가능

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1. ])

In [38]:
np.arange(0, 1.1, 0.1).tolist()     # tolist를 사용해 리스트로 만들 수 있음

[0.0,
 0.1,
 0.2,
 0.30000000000000004,
 0.4,
 0.5,
 0.6000000000000001,
 0.7000000000000001,
 0.8,
 0.9,
 1.0]

In [39]:
np.arange(0, 1.1, 0.1).tolist()[3] == 0.3
# 실수는 우리가 원하는 값을 정확하게 표현하지 못함
# 확실하게 확인하려면 아래 방법사용

False

In [41]:
# 두 실수의 비교는 차이가 아주 작냐를 물어보는 것이 올바른 방법!
np.abs(np.arange(0, 1.1, 0.1).tolist()[3] - 0.3) < 1e-8     # 10의 -8승과 같냐고 물어보면 TRUE

True

In [42]:
# ones, zeros, empty - 괄호 두개 사용.
# 모든 데이터가 0 또는 1로만 이루어진 배열을 만들어 내는 명령어
a = np.zeros((5,), dtype = np.int8)     # 괄호 1개만 쓰면 1행짜리를 만들수있다.
a

array([0, 0, 0, 0, 0], dtype=int8)

In [43]:
b = np.ones((2, 4), dtype = np.int8)
b

array([[1, 1, 1, 1],
       [1, 1, 1, 1]], dtype=int8)

In [44]:
np.empty((2, 5))

array([[0.1, 0.2, 0.3, 0.4, 0.5],
       [0.6, 0.7, 0.8, 0.9, 1. ]])

In [45]:
a = np.arange(24).reshape(4, -1)
np.ones_like(a)     # _like는 지정된 array의 shape 크기만큼 지정된 값으로 채워 array 반환

array([[1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1]])

In [46]:
np.zeros_like(a)

array([[0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0]])

In [47]:
# 단위 행렬: identity
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [56]:
# eye - 대각선이 1인 행렬
np.eye(3, 5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.]])

In [58]:
np.eye(N = 3, M = 5, k = -1)

array([[0., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.]])

In [57]:
np.eye(3, 5, 2)

array([[0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

- Random sampling

In [59]:
# 
np.random.seed(2021)
np.random.uniform(0, 1, 10).reshape(2, 5)       # uniform 랜덤으로 동일한 확률로 끄집어내겟다!

array([[0.60597828, 0.73336936, 0.13894716, 0.31267308, 0.99724328],
       [0.12816238, 0.17899311, 0.75292543, 0.66216051, 0.78431013]])

In [60]:
# 정규 분포
np.random.normal(0, 1, 10).reshape(2, 5)        # normal 정규분포

array([[ 0.10641374,  0.42215483,  0.12420684, -0.83795346,  0.4090157 ],
       [ 0.10275122, -1.90772239,  1.1002243 , -1.40232506, -0.22508127]])

In [61]:
# 이항분포, 포아송분포, t-분포, F-분포
np.random.binomial(100, 0.5, 10)

array([46, 53, 57, 48, 57, 44, 40, 57, 54, 49])