In [1]:
import numpy as np

### 1. 넘파이를 사용하여 다음과 같은 행렬을 만드시오.
- 10 20 30 40
- 50 60 70 80

In [4]:
a = [[10, 20, 30, 40], [50, 60, 70, 80]]
np.array(a)

array([[10, 20, 30, 40],
       [50, 60, 70, 80]])

### 2. 다음 행렬과 같은 행렬이 있다.
- m = np.array([[0,1,2,3,4],
              [5,6,7,8,9],
              [10,11,12,13,14]])
- 1) 이 행렬에서 값 7을 인덱싱한다.
- 2) 이 행렬에서 값 14를 인덱싱한다.
- 3) 이 행렬에서 배열 [6,7]을 슬라이싱한다.
- 4) 이 행렬에서 배열 [7,12]를 슬라이싱한다.
- 5) 이 행렬에서 배열 [[3,4], [8,9]]를 슬라이싱한다.

In [5]:
m = np.array([[0,1,2,3,4],
              [5,6,7,8,9],
              [10,11,12,13,14]])
m[1,2]
m[2,-1]         # m[-1, -1]
m[1, 1:3]
m[1,2], m[2,2]  # m[1:, 2]
m[:2, 3:5]      # m[:2, 3:]

7

### 3. 2번의 행렬 m을 1차원 벡터 f로 변환한 후 다음의 문제를 푸시오
- 1) 이 배열에서 3의 배수를 찾아라
- 2) 이 배열에서 4로 나누면 1이 남는 수를 찾아라
- 3) 이 배열에서 3으로 나누면 나누어지고 4로 나누면 1이 남는 수를 찾아라

In [93]:
f = m.flatten()

f[f % 3 == 0] 
f[f % 4 == 1]
f[np.logical_and(f % 3 == 0, f % 4 == 1)]

array([9])

### 4. 값을 직접 입력하지 말고 행렬을 만드시오
- 2 1 0 0 0
- 3 2 1 0 0
- 0 3 2 1 0
- 0 0 3 2 1
- 0 0 0 3 2

In [6]:
np.eye(5)       # np.eye(5, 5, k=-1)*3 + np.eye(5,5) * 2 + np.eye(5, 5, k=1)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [2]:
np.eye(5, 5, k=-1)*3 + np.eye(5,5) * 2 + np.eye(5, 5, k=1)

array([[2., 1., 0., 0., 0.],
       [3., 2., 1., 0., 0.],
       [0., 3., 2., 1., 0.],
       [0., 0., 3., 2., 1.],
       [0., 0., 0., 3., 2.]])

### 5. 0에서 10까지 랜덤 실수값으로이루어진 5 x 6 형태의 데이터 행렬을 만들고 이 데이터에 대해 다음과 같은 값을 구하시오.
- 1) 전체의 최댓값
- 2) 각 행의 합
- 3) 각 행의 최댓값
- 4) 각 열의 평균
- 5) 각 열의 최솟값

In [82]:
b = np.random.uniform(0, 10, (5,6))

b.max()             # 전체의 최댓값
b.sum(axis = 1)     # 각 행의 합
b.max(axis = 1)     # 각 행의 최댓값
b.mean(axis = 0)    # 각 열의 평균
b.min(axis = 0)     # 각 열의 최솟값

array([[5.27146881, 8.04382915, 2.95075894, 1.83338551, 0.1973246 ,
        7.43321232],
       [0.38293404, 4.33679669, 8.32084761, 0.13458558, 5.09335392,
        4.795487  ],
       [0.29654941, 0.11428527, 3.31844   , 0.61431079, 5.98173508,
        8.85920254],
       [4.12133775, 0.38272199, 0.80842404, 0.81914542, 8.09367334,
        8.00694003],
       [0.16909811, 8.61294325, 9.11300224, 4.00876685, 2.86890698,
        8.43044885]])

In [ ]:
#### -답
np.random.seed(2021)
m = np.random.uniform(0, 10, 30).reshape(5, 6).round(4)
m

np.max(m)
np.sum(m, axis = 1)
np.max(m, axis = 1)
np.mean(m, axis = 0)
np.min(m, axis = 0)

### 6. 다음 배열은 첫번째 행(row), 두번째 행에 영어 성적, 세번째 행에 수학 성적을 적은 배열이다. 영어 성적을 기준으로 각 열(column)을 재정렬하시오.
- array([[1, 2, 3, 4],
-        [46, 99, 100, 71],
-        [81, 59, 90, 100]])

In [8]:
a = [[1, 2, 3, 4], [46, 99, 100, 71], [81, 59, 99, 100]]
np.array(a)


array([[  1,   2,   3,   4],
       [ 46,  99, 100,  71],
       [ 81,  59,  99, 100]])

In [ ]:
#### - 답
score = np.array([[1, 2, 3, 4],
                  [46, 99, 100, 71],
                  [81, 59, 99, 100]])
np.sort(score, axis = 1, order=)


s = np.argsort(score[1])        # 오름차순
s[::-1]                         # 내림차순


score[:, s]
score[:, np.argsort(score[1])]      # 위에 처럼 단계 안나누고 한번에 사용하는법 
score[:, np.argsort(score[1])[::-1]]    # 내림차순 한꺼번에 수행하기

- argmax() : 컬럼의 최대값인 인덱스의 위치값...
- argsort() : 컬럼의 인덱스의 위치값 내림차순정렬!!  ※ 그냥인덱스가아니라 컬럼의 위치값임

### 7. 주사위를 100번 던지는 가상 실험을 파이썬으로 작성하고, 던져서 나오는 숫자의 평균을 구하시오

In [95]:
a = np.random.binomial(1, 0.5, 100)     # 앞 또는 뒤 (n =1)가 나올확률(0.5)을 100번(100)  
# 이거는 동전 구하는거

In [ ]:
#### - 답
np.random.seed(2021)
dice = np.random.randint(1, 7, 100)     # 주사위 1~6까지 100번
dice

np.mean(dice)

### 8. 가격이 10,000원인 주식이 있다. 이 주식의 일간 수익률(%)은 기댓값이 0%이고 표준편차가 1%인 표준 정규 분포를 따른다고 할때, 250일 동안의 주가를 무작위로 생성하시오.
- 일간 수익률 = 누적
-10,000 +1% → 10,100 →  -1% 9,999
        -1% →   9,900 →  +1% 9,999

In [10]:
#### - 답
np.random.seed(2021)
price = 10000
rate = np.random.normal(0, 1, 10)
for i in range(10):
    price += np.round(price + rate[i] * 0.01)       # 누적
    print(price, end=", ")

20000.0, 40000.0, 80000.0, 160000.0, 320000.0, 640000.0, 1280000.0, 2560000.0, 5120000.0, 10240000.0, 

In [13]:
np.random.seed(2021)
price_list = []
rate = np.random.normal(0, 1, 250)
price = 10000
for i in range(250):
    price += np.round(price * rate[i] * 0.01)
    price_list.append(price)
price_array = np.array(price_list, int)     # array는 갯수, 계산에 취약하다다

In [14]:
print(price_array[:10])     # 앞뒤로 10개 뽑기
print(price_array[-10:])

[10149 10218 10175 10093 10149 10077 10191 10257 10268 10311]
[12072 12210 12255 12359 12292 12262 12136 12010 11984 12113]


In [3]:
#### - 답 : 수민버전
stock = [10000]
np.random.seed(2021)
for i in range(250):
    rate = np.random.normal(0, 1, 1)/100        # (평균, 표준편차, 뽑는 횟수)
    price = int(np.round(stock[0]*rate + stock[-1], 0)) # 초기자금에 rate곱한거(수익률) + 최종자금)
    stock.append(price)     # 원자금 stock에 수익률 price를 더한다
print(stock)

[10000, 10149, 10217, 10175, 10094, 10150, 10079, 10192, 10257, 10268, 10310, 10322, 10238, 10279, 10289, 10098, 10208, 10068, 10045, 9911, 9941, 9869, 10123, 10255, 10262, 10236, 10250, 10365, 10503, 10456, 10508, 10657, 10805, 10878, 10839, 10867, 10872, 10768, 10752, 10473, 10509, 10533, 10581, 10602, 10694, 10553, 10675, 10620, 10711, 10613, 10550, 10633, 10505, 10470, 10362, 10459, 10500, 10487, 10420, 10542, 10449, 10591, 10579, 10650, 10722, 10736, 10671, 10604, 10691, 10791, 10754, 10867, 10946, 10771, 10690, 10549, 10469, 10549, 10725, 10717, 10759, 10775, 10769, 10715, 10805, 10827, 10955, 11018, 11054, 11418, 11298, 11165, 11291, 11226, 11451, 11350, 11337, 11294, 11337, 11413, 11314, 11240, 11286, 11412, 11368, 11422, 11479, 11435, 11512, 11560, 11472, 11404, 11449, 11376, 11232, 11447, 11452, 11517, 11410, 11434, 11471, 11512, 11632, 11740, 11768, 11861, 11894, 12073, 11978, 11921, 11946, 11997, 11953, 12132, 12150, 12188, 12239, 12298, 12488, 12548, 12536, 12551, 12608, 1