In [1]:
import numpy as np

### 1. 넘파이를 사용하여 다음과 같은 행렬을 만드시오.
- 10 20 30 40
- 50 60 70 80

In [4]:
a = [[10, 20, 30, 40], [50, 60, 70, 80]]
np.array(a)

array([[10, 20, 30, 40],
       [50, 60, 70, 80]])

### 2. 다음 행렬과 같은 행렬이 있다.
- m = np.array([[0,1,2,3,4],
              [5,6,7,8,9],
              [10,11,12,13,14]])
- 1) 이 행렬에서 값 7을 인덱싱한다.
- 2) 이 행렬에서 값 14를 인덱싱한다.
- 3) 이 행렬에서 배열 [6,7]을 슬라이싱한다.
- 4) 이 행렬에서 배열 [7,12]를 슬라이싱한다.
- 5) 이 행렬에서 배열 [[3,4], [8,9]]를 슬라이싱한다.

In [5]:
m = np.array([[0,1,2,3,4],
              [5,6,7,8,9],
              [10,11,12,13,14]])
m[1,2]
m[2,-1]
m[1, 1:3]
m[1,2], m[2,2]
m[:2, 3:5]

7

### 3. 2번의 행렬 m을 1차원 벡터 f로 변환한 후 다음의 문제를 푸시오
- 1) 이 배열에서 3의 배수를 찾아라
- 2) 이 배열에서 4로 나누면 1이 남는 수를 찾아라
- 3) 이 배열에서 3으로 나누면 나누어지고 4로 나누면 1이 남는 수를 찾아라

In [93]:
f = m.flatten()

f[f % 3 == 0] 
f[f % 4 == 1]
f[np.logical_and(f % 3 == 0, f % 4 == 1)]

array([9])

### 4. 값을 직접 입력하지 말고 행렬을 만드시오
- 2 1 0 0 0
- 3 2 1 0 0
- 0 3 2 1 0
- 0 0 3 2 1
- 0 0 0 3 2

In [56]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

### 5. 0에서 10까지 랜덤 실수값으로이루어진 5 x 6 형태의 데이터 행렬을 만들고 이 데이터에 대해 다음과 같은 값을 구하시오.
- 1) 전체의 최댓값
- 2) 각 행의 합
- 3) 각 행의 최댓값
- 4) 각 열의 평균
- 5) 각 열의 최솟값

In [82]:
b = np.random.uniform(0, 10, (5,6))

b.max()             # 전체의 최댓값
b.sum(axis = 1)     # 각 행의 합
b.max(axis = 1)     # 각 행의 최댓값
b.mean(axis = 0)    # 각 열의 평균
b.min(axis = 0)     # 각 열의 최솟값

array([[5.27146881, 8.04382915, 2.95075894, 1.83338551, 0.1973246 ,
        7.43321232],
       [0.38293404, 4.33679669, 8.32084761, 0.13458558, 5.09335392,
        4.795487  ],
       [0.29654941, 0.11428527, 3.31844   , 0.61431079, 5.98173508,
        8.85920254],
       [4.12133775, 0.38272199, 0.80842404, 0.81914542, 8.09367334,
        8.00694003],
       [0.16909811, 8.61294325, 9.11300224, 4.00876685, 2.86890698,
        8.43044885]])

### 6. 다음 배열은 첫번째 행(row), 두번째 행에 영어 성적, 세번째 행에 수학 성적을 적은 배열이다. 영어 성적을 기준으로 각 열(column)을 재정렬하시오.
- array([[1, 2, 3, 4],
-        [46, 99, 100, 71],
-        [81, 59, 90, 100]])

In [ ]:
a =

### 7. 주사위를 100번 던지는 가상 실험을 파이썬으로 작성하고, 던져서 나오는 숫자의 평균을 구하시오

In [66]:
a = np.random.binomial(100, 0.5, 10)
a.mean()

49.2

### 8. 가격이 10,000원인 주식이 있다. 이 주식의 일간 수익률(%)은 기댓값이 0%이고 표준편차가 1%인 표준 정규 분포를 따른다고 할때, 250일 동안의 주가를 무작위로 생성하시오.